kafkaPool: nav-dev
fiaSuperbrukerGroup: 02b25498-1a81-45b5-84cb-876a8899c809
fiaSaksbehandlerGroup: e00f4248-2d26-4645-bf94-22d47623a51e
fiaLesetilgangGroup: 30f17df5-c36c-4ad7-b862-48f56c95ebb2
teamPiaGroup: 02b25498-1a81-45b5-84cb-876a8899c809
dbTier: db-f1-micro
dbAutoresizeDisk: false
limitsCpu: 2000m
limitsMemory: 1Gi
requestsCpu: 100m
requestsMemory: 256Mi
salesforceTokenHost: https://test.salesforce.com
journalpostHost: dokarkiv-q2.dev-fss-pub.nais.io
journalpostApi: https://dokarkiv-q2.dev-fss-pub.nais.io/rest/journalpostapi/v1
