apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "lydia-api"
  namespace: "pia"
  labels:
    "team": "pia"
spec:
  image: {{image}}
  resources:
    limits:
      cpu: {{limitsCpu}}
      memory: {{limitsMemory}}
    requests:
      cpu: {{requestsCpu}}
      memory: {{requestsMemory}}
  liveness:
    path: "/internal/isalive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/internal/isready"
    port: 8080
    initialDelay: 20
    timeout: 60
  prometheus:
    enabled: true
    path: "/metrics"
  accessPolicy:
    outbound:
      rules:
        - application: pia-pdfgen
      external:
        - host: {{journalpostHost}}
        - host: data.ssb.no
        - host: salesforce.com
    inbound:
      rules:
        - application: lydia-radgiver-frontend
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: {{fiaSuperbrukerGroup}}
          - id: {{fiaSaksbehandlerGroup}}
          - id: {{fiaLesetilgangGroup}}
          - id: {{teamPiaGroup}}
        extra:
          - "NAVident"
  gcp:
    sqlInstances:
    - type: POSTGRES_12
      diskAutoresize: {{dbAutoresizeDisk}}
      tier: {{dbTier}}
      databases:
        - name: "lydia-api-db"
  kafka:
    pool: {{kafkaPool}}
  envFrom:
    - secret: fia-salesforce
  env:
    - name: CONSUMER_LOOP_DELAY
      value: "1000"
    - name: SSB_NARINGS_URL
      value: "https://data.ssb.no/api/klass/v1//versions/30.json?language=nb"
    - name: FIA_SUPERBRUKER_GROUP_ID
      value: {{fiaSuperbrukerGroup}}
    - name: FIA_SAKSBEHANDLER_GROUP_ID
      value: {{fiaSaksbehandlerGroup}}
    - name: FIA_LESETILGANG_GROUP_ID
      value: {{fiaLesetilgangGroup}}
    - name: TEAM_PIA_GROUP_ID
      value: {{teamPiaGroup}}
    - name: SALESFORCE_TOKEN_HOST
      value: {{salesforceTokenHost}}
    - name: JOURNALPOST_V1_URL
      value: {{journalpostApi}}
    - name: PIA_PDFGEN_URL
      value: http://pia-pdfgen
