apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "lydia-api"
  namespace: "pia"
  labels:
    "team": "pia"
spec:
  image: {{image}}
  resources:
    limits:
      cpu: {{limitsCpu}}
      memory: {{limitsMemory}}
    requests:
      cpu: {{requestsCpu}}
      memory: {{requestsMemory}}
  liveness:
    path: "/internal/isalive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/internal/isready"
    port: 8080
    initialDelay: 20
    timeout: 60
  prometheus:
    enabled: true
    path: "/metrics"
  accessPolicy:
    outbound:
      external:
        - host: "data.ssb.no"
        - host: "salesforce.com"
    inbound:
      rules:
        - application: lydia-radgiver-frontend
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: {{fiaSuperbrukerGroup}}
          - id: {{fiaSaksbehandlerGroup}}
          - id: {{fiaLesetilgangGroup}}
          - id: {{teamPiaGroup}}
        extra:
          - "NAVident"
  gcp:
    sqlInstances:
    - type: POSTGRES_14
      diskAutoresize: {{dbAutoresizeDisk}}
      tier: {{dbTier}}
      databases:
        - name: "lydia-api-db"
  kafka:
    pool: {{kafkaPool}}
  envFrom:
    - secret: fia-salesforce
  env:
    - name: IA_SAK_TOPIC
      value: pia.ia-sak-v1
    - name: IA_SAK_STATISTIKK_TOPIC
      value: pia.ia-sak-statistikk-v1
    - name: IA_SAK_STATUS_TOPIC
      value: pia.ia-sak-status-v1
    - name: IA_SAK_LEVERANSE_TOPIC
      value: pia.ia-sak-leveranse-v1
    - name: SPORREUNDERSOKELSE_TOPIC
      value: pia.sporreundersokelse-v1
    - name: SPORREUNDERSOKELSE_SVAR_TOPIC
      value: pia.sporreundersokelse-svar-v1
    - name: BRREG_OPPDATERING_TOPIC
      value: pia.brreg-oppdatering
    - name: BRREG_ALLE_VIRKSOMHETER_TOPIC
      value: pia.brreg-alle-virksomheter
    - name: STATISTIKK_METADATA_VIRKSOMHET_TOPIC
      value: arbeidsgiver.sykefravarsstatistikk-metadata-virksomhet-v1
    - name: STATISTIKK_LAND_TOPIC
      value: arbeidsgiver.sykefravarsstatistikk-land-v1
    - name: STATISTIKK_SEKTOR_TOPIC
      value: arbeidsgiver.sykefravarsstatistikk-sektor-v1
    - name: STATISTIKK_BRANSJE_TOPIC
      value: arbeidsgiver.sykefravarsstatistikk-bransje-v1
    - name: STATISTIKK_NARING_TOPIC
      value: arbeidsgiver.sykefravarsstatistikk-naring-v1
    - name: STATISTIKK_NARINGSKODE_TOPIC
      value: arbeidsgiver.sykefravarsstatistikk-naringskode-v1
    - name: STATISTIKK_VIRKSOMHET_TOPIC
      value: arbeidsgiver.sykefravarsstatistikk-virksomhet-v1
    - name: STATISTIKK_VIRKSOMHET_GRADERING_TOPIC
      value: arbeidsgiver.sykefravarsstatistikk-virksomhet-gradert-v1
    - name: JOBBLYTTER_TOPIC
      value: pia.jobblytter-v1
    - name: CONSUMER_LOOP_DELAY
      value: "1000"
    - name: SSB_NARINGS_URL
      value: "https://data.ssb.no/api/klass/v1//versions/30.json?language=nb"
    - name: FIA_SUPERBRUKER_GROUP_ID
      value: {{fiaSuperbrukerGroup}}
    - name: FIA_SAKSBEHANDLER_GROUP_ID
      value: {{fiaSaksbehandlerGroup}}
    - name: FIA_LESETILGANG_GROUP_ID
      value: {{fiaLesetilgangGroup}}
    - name: TEAM_PIA_GROUP_ID
      value: {{teamPiaGroup}}
    - name: SALESFORCE_TOKEN_HOST
      value: {{salesforceTokenHost}}
