apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "lydia-api"
  namespace: "pia"
  labels:
    "team": "pia"
spec:
  image: {{image}}
  resources:
    limits:
      cpu: {{limitsCpu}}
      memory: {{limitsMemory}}
    requests:
      cpu: {{requestsCpu}}
      memory: {{requestsMemory}}
  liveness:
    path: "/internal/isalive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/internal/isready"
    port: 8080
    initialDelay: 20
    timeout: 60
  prometheus:
    enabled: true
    path: "/metrics"
  accessPolicy:
    inbound:
      rules:
        - application: lydia-radgiver-frontend
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: {{fiaSuperbrukerGroup}}
          - id: {{fiaSaksbehandlerGroup}}
          - id: {{fiaLesetilgangGroup}}
          - id: {{teamPiaGroup}}
        extra:
          - "NAVident"
  gcp:
    sqlInstances:
    - type: POSTGRES_12
      diskAutoresize: {{dbAutoresizeDisk}}
      tier: {{dbTier}}
      databases:
        - name: "lydia-api-db"
  kafka:
    pool: {{kafkaPool}}
  env:
    - name: IA_SAK_HENDELSE_TOPIC
      value: pia.ia-sak-hendelse-v1
    - name: IA_SAK_TOPIC
      value: pia.ia-sak-v1
    - name: BRREG_OPPDATERING_TOPIC
      value: pia.brreg-oppdatering
    - name: STATISTIKK_TOPIC
      value: arbeidsgiver.sykefravarsstatistikk-v1
    - name: STATISTIKK_LAND_TOPIC
      value: arbeidsgiver.sykefravarsstatistikk-land-v1
    - name: BRREG_UNDERENHET_URL
      value: "https://data.brreg.no/enhetsregisteret/api/underenheter/lastned"
    - name: CONSUMER_LOOP_DELAY
      value: "1000"
    - name: SSB_NARINGS_URL
      value: "https://data.ssb.no/api/klass/v1//versions/30.json?language=nb"
    - name: FIA_SUPERBRUKER_GROUP_ID
      value: {{fiaSuperbrukerGroup}}
    - name: FIA_SAKSBEHANDLER_GROUP_ID
      value: {{fiaSaksbehandlerGroup}}
    - name: FIA_LESETILGANG_GROUP_ID
      value: {{fiaLesetilgangGroup}}
    - name: TEAM_PIA_GROUP_ID
      value: {{teamPiaGroup}}
