apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "lydia-api"
  namespace: "pia"
  labels:
    "team": "pia"
spec:
  image: {{image}}
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  liveness:
    path: "/internal/isalive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/internal/isready"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
  accessPolicy:
    inbound:
      rules:
        - application: lydia-radgiver-frontend
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: {{azureAdGroup}}
          - id: {{fiaSuperbrukerGroup}}
          - id: {{fiaSaksbehandlerGroup}}
          - id: {{fiaLesetilgangGroup}}
        extra:
          - "NAVident"
  gcp:
    sqlInstances:
    - type: POSTGRES_12
      databases:
        - name: "lydia-api-db"
  kafka:
    pool: {{kafkaPool}}
  env:
    - name: STATISTIKK_TOPIC
      value: {{statistikkTopic}}
    - name: BRREG_UNDERENHET_URL
      value: "https://data.brreg.no/enhetsregisteret/api/underenheter/lastned"
    - name: CONSUMER_LOOP_DELAY
      value: "1000"
    - name: SSB_NARINGS_URL
      value: "https://data.ssb.no/api/klass/v1//versions/30.json?language=nb"