/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package no.nav.lydia

import com.auth0.jwk.JwkProviderBuilder
import io.ktor.application.Application
import io.ktor.application.call
import io.ktor.application.install
import io.ktor.application.log
import io.ktor.auth.Authentication
import io.ktor.auth.authenticate
import io.ktor.auth.jwt.JWTPrincipal
import io.ktor.auth.jwt.jwt
import io.ktor.features.ContentNegotiation
import io.ktor.features.StatusPages
import io.ktor.http.HttpStatusCode
import io.ktor.metrics.micrometer.MicrometerMetrics
import io.ktor.response.respond
import io.ktor.routing.IgnoreTrailingSlash
import io.ktor.routing.routing
import io.ktor.serialization.json
import io.ktor.server.engine.addShutdownHook
import io.ktor.server.engine.embeddedServer
import io.ktor.server.engine.stop
import io.ktor.server.netty.Netty
import no.nav.lydia.appstatus.Metrics
import no.nav.lydia.appstatus.healthChecks
import no.nav.lydia.appstatus.metrics
import no.nav.lydia.sykefraversstatistikk.SykefraversstatistikkRepository
import no.nav.lydia.sykefraversstatistikk.api.geografi.GeografiService
import no.nav.lydia.sykefraversstatistikk.api.sykefraversstatistikk
import no.nav.lydia.sykefraversstatistikk.import.StatistikkConsumer
import no.nav.lydia.virksomhet.VirksomhetRepository
import no.nav.lydia.virksomhet.VirksomhetService
import java.util.concurrent.TimeUnit
import javax.sql.DataSource

fun main() {
    startLydiaBackend()
}

fun startLydiaBackend() {
    val naisEnv = NaisEnvironment()
    val dataSource = createDataSource(database = naisEnv.database)
    runMigration(dataSource = dataSource)

    statistikkConsumer(
        kafka = naisEnv.kafka,
        sykefraversstatistikkRepository = SykefraversstatistikkRepository(dataSource = dataSource)
    )

    embeddedServer(Netty, port = 8080) {
        lydiaRestApi(security = naisEnv.security, dataSource = dataSource)
    }.also {
        // https://doc.nais.io/nais-application/good-practices/#handles-termination-gracefully
        it.addShutdownHook {
            it.stop(3, 5, TimeUnit.SECONDS)
        }
    }.start(wait = true)
}

fun Application.lydiaRestApi(security: Security, dataSource: DataSource) {
    install(ContentNegotiation) {
        json()
    }
    install(IgnoreTrailingSlash)

    install(MicrometerMetrics) {
        registry = Metrics.appMicrometerRegistry
    }

    val jwkProvider = JwkProviderBuilder(security.azureConfig.jwksUri)
        .cached(10, 24, TimeUnit.HOURS)
        .rateLimited(10, 1, TimeUnit.MINUTES)
        .build()
    install(Authentication) {
        jwt {
            verifier(jwkProvider, security.azureConfig.issuer)
            validate { credentials ->
                try {
                    requireNotNull(credentials.payload.audience) {
                        "Auth: Missing audience in token"
                    }
                    require(credentials.payload.audience.contains(security.azureConfig.audience)) {
                        "Auth: Valid audience not found in claims"
                    }
                    JWTPrincipal(credentials.payload)
                } catch (e: Throwable) {
                    log.error("Feil under autentisering")
                    log.error(e.message)
                    null
                }
            }
        }
    }
    install(StatusPages) {
        exception<Throwable> { cause ->
            log.error("Det har skjedd en feil bro!", cause)
            call.respond(HttpStatusCode.InternalServerError)
        }
    }

    val virksomhetRepository = VirksomhetRepository(dataSource)
    val sykefraversstatistikkRepository = SykefraversstatistikkRepository(dataSource)
    val virksomhetService = VirksomhetService(virksomhetRepository)
    val geografiService = GeografiService()

    routing {
        healthChecks()
        metrics()
        authenticate {
            sykefraversstatistikk(virksomhetService, geografiService, sykefraversstatistikkRepository)
        }
    }
}

fun statistikkConsumer(kafka: Kafka, sykefraversstatistikkRepository: SykefraversstatistikkRepository) =
    StatistikkConsumer.apply {
        create(kafka = kafka, sykefraversstatistikkRepository = sykefraversstatistikkRepository)
        run()
    }

