apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: ia-sak-status-v1
  namespace: pia
  labels:
    team: pia
spec:
  pool: {{kafkaPool}}
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: compact  # delete, compact, compact,delete
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 17520  # 2 år
  acl:
    - team: pia
      application: lydia-api
      access: readwrite   # read, write, readwrite
    - team: pia
      application: fia-arbeidsgiver
      access: read   # read, write, readwrite
    - team: pia
      application: pia-devops
      access: read
